### ISSUE TITLE
move all littered content to support folder

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-cns-testdrive#141]
We have content littered in several locations. If a script, file, or etc. needs to be used during the exercises, it should go into the repo in the `support` folder. For generated files that will be used (like the groupsync config), the `write_files` section of cloud-init should be relocated such that this repo is cloned *first*, and then the files are written out.

**Comment by thoraxe** [comment]
@dmesser @cooktheryan I feel like this is pretty much fixed, no?

**Comment by dmesser** [comment]
Ack
