### ISSUE TITLE
[mod cns management] chicken-egg problem with combined automation/test playbook and adding hosts to group

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-cns-testdrive#152]
when running the automation/tests in a single playbook, the inventory is loaded on playbook start. When the test of items in the fact `new_cns_nodes_internal_fqdn` is executed against the group `cns`, Ansible hasn't learned of these hosts yet, so this test fails...

**Comment by dmesser** [comment]
Fixed by #155
