### ISSUE TITLE
bad wording on root kubeconfig

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-cns-testdrive#178]
https://github.com/openshift/openshift-cns-testdrive/blame/master/labguide/installation.adoc#L98-L102

**Comment by dmesser** [comment]
Not quite sure what the solution here should look like. I think if we advise how vitally important it is to either protect the systems root account or remove this pre-configured config, we should also show how to do the latter.

**Comment by thoraxe** [comment]
I read it again after having not read it for a long time, and I don't see a problem with it. I'm not sure what to do here.
