### ISSUE TITLE
fix container-native storage references

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-cns-testdrive#179]
https://github.com/openshift/openshift-cns-testdrive/blame/master/labguide/cns-deploy.adoc#L2

https://github.com/openshift/openshift-cns-testdrive/blame/master/labguide/cns-deploy.adoc#L3

https://github.com/openshift/openshift-cns-testdrive/blame/master/labguide/cns-deploy.adoc#L219

https://github.com/openshift/openshift-cns-testdrive/blame/master/labguide/cns-deploy.adoc#L407

https://github.com/openshift/openshift-cns-testdrive/blame/master/labguide/cns-deploy.adoc#L409

**Comment by dmesser** [comment]
fixed by #205
