### ISSUE TITLE
update heketi secret wording

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-cns-testdrive#184]
https://github.com/openshift/openshift-cns-testdrive/blame/master/labguide/cns-deploy.adoc#L593

Change 'The namespace in which we created the secret file Before' to 'The namespace in which we created the heketi secret fusing the cns-secret.yaml file'

**Comment by dmesser** [comment]
Not fixed. The secret belongs to the storage class and not heketi. I believe the heketi deployment has it's own secrets, not to be confused with this.
