### ISSUE TITLE
bad links

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-cns-testdrive#186]
https://github.com/openshift/openshift-cns-testdrive/blame/master/labguide/app-mgmt-basics.adoc#L170

Should be:
https://docs.openshift.com/container-platform/3.5/architecture/core_concepts/pods_and_services.html#services

https://github.com/openshift/openshift-cns-testdrive/blame/master/labguide/app-mgmt-basics.adoc#L322

Should be:
https://docs.openshift.com/container-platform/3.5/architecture/core_concepts/deployments.html

**Comment by dmesser** [comment]
Fixed in #220
