### ISSUE TITLE
Ansible playbook for OCP installation

### ISSUE THREAD

**Issue by kmurudi** [openshift/openshift-cns-testdrive#20]
For the user to be able to use ansible-playbook and access the config.yml playbook from the openshift-ansible git repository, it should be present in the master host. The inventory file is present but the ansible playbook needed to run the advanced installation is not. 

Also, two instances present of node01 in the list of EC-2 Instances

**Comment by cooktheryan** [comment]
For the config.yaml the playbook should be executed as 

ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/byo/config.yaml

Unless we want to use the playbooks from git but I worry about maintaining versions

**Comment by kmurudi** [comment]
Alright, that works! thanks
