### ISSUE TITLE
listdefs don't bold when inserted at beginning of line

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-cns-testdrive#200]
https://github.com/openshift/openshift-cns-testdrive/blame/master/labguide/ldap-groupsync.adoc#L67-L68

Probably need to widen the main lab area before fixing this, though.

**Comment by dmesser** [comment]
Correct. Also the listdef syntax only works at the end of a line.

**Comment by dmesser** [comment]
Fixed in #220

**Comment by thoraxe** [comment]
Since #220 was merged, I'm closing...
