### ISSUE TITLE
Module 8: Bad example of 'heketi-cli node info <nodeID>

### ISSUE THREAD

**Issue by netzzer** [openshift/openshift-cns-testdrive#213]
This example below in Module 8 s missing the 2nd brick device name (should be Name:/dev/xvde which was created in prior lab task). 
heketi-cli node info 33e0045354db4be29b18728cbe817605

Node Id: 33e0045354db4be29b18728cbe817605
State: online
Cluster Id: ca777ae0285ef6d8cd7237c862bd591c
Zone: 1
Management Hostname: node04.internal.aws.testdrive.openshift.com
Storage Hostname: 10.0.1.59
Devices:
Id:01c94798bf6b1af87974573b420c4dff   Name:/dev/xvdd           State:online    Size (GiB):9       Used (GiB):1       Free (GiB):8
Id:da91a2f1c9f62d9916831de18cc09952   Name:           State:online    Size (GiB):9       Used (GiB):1       Free (GiB):8

**Comment by dmesser** [comment]
Fixed in #220
