### ISSUE TITLE
Module 9: Playbook infra-mgmt_automation.yaml is missing

### ISSUE THREAD

**Issue by netzzer** [openshift/openshift-cns-testdrive#214]
Mod 9, playbook infra-mgmt_automation.yaml is missing. I did run the infra-mgmt_verify.yaml and the 3 extra nodes were created but had to manually exit this playbook, did not look like it would complete.

**Comment by dmesser** [comment]
At which exact Ansible task is it hangin?

**Comment by netzzer** [comment]
Tried again infra-mgmt_verify.yaml after first doing Mod1-Mod3 and Mod 6. Worked this time, I may have not waited long enough for some of the longer running tasks the first time. Still, the infra-mgmt_automation.yaml is missing and this should be fixed.

**Comment by dmesser** [comment]
@thoraxe pls confirm infra-mgmt_automation.yml is now completed part of  tests/infra-mgmt_verify.yaml

**Comment by dmesser** [comment]
Fixed in #220
