### ISSUE TITLE
Module 8 [RFE] - add 'oc volume dc/docker-registry' before and after PVC creation

### ISSUE THREAD

**Issue by netzzer** [openshift/openshift-cns-testdrive#218]
Adding into Lab Guide executing 'oc volume dc/docker-registry' before and after PVC creation.
Before:
deploymentconfigs/docker-registry
  empty directory as registry-storage
    mounted at /registry
After:
deploymentconfigs/docker-registry
  pvc/registry-storage (allocated 10GiB) as registry-storage
    mounted at /registry

**Comment by dmesser** [comment]
solved by update 3.9
