### ISSUE TITLE
Use drain instead of evacuate

### ISSUE THREAD

**Issue by dmesser** [openshift/openshift-cns-testdrive#234]
https://github.com/openshift/openshift-cns-testdrive/blob/84e0212b31ffa3a5d37c13c4cacaaea694a5d751/labguide/infra-mgmt-basics.adoc#L676

There is a deprecation message from this command asking people to use `drain` instead of `evacuate`.

**Comment by dmesser** [comment]
The official 3.6 docs still recommend `evacuate`. `drain` however is probably also more stable for automation, since it can ignore daemonsets and pods with emptyDir. 
The lab guide and automation should be rewritten to use `drain` likely with `--ignore-daemonsets=true`

**Comment by thoraxe** [comment]
#317 

Can someone test?
