### ISSUE TITLE
Disable registry console installation

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-cns-testdrive#239]

**Comment by dmesser** [comment]
Looks like this hard-coded and tied to `openshift_hosted_manage_registry=true`. If I set it to false no registry will be deployed at all. I am trying to give it a shot by making openshift-ansible/playbooks/common/openshift-cluster/cockpit-ui.yml an empty file.

**Comment by thoraxe** [comment]
If it's hard coded we should probably just figure out why the deployment fails instead of hacking it.

**Comment by dmesser** [comment]
I agree. We need to fix the evacuation step and not fiddle with the installer. Closing this in favor of #234
