### ISSUE TITLE
create_failed on cloud formation

### ISSUE THREAD

**Issue by kmurudi** [openshift/openshift-cns-testdrive#26]
classes - 'OpenShift Test Drive for Administrators' and 
'ocp-admin-testdrive-master-branch'
are not being built successfully when opening the AWS console. The CloudFormation service shows the error of 'create_failed'

**Comment by thoraxe** [comment]
@kmurudi is this still true?

**Comment by cooktheryan** [comment]
I believe if we merge the pr I have in place the Ami should be shared with
all the qwiklabs accounts and will resolve this.

**Comment by kmurudi** [comment]
I just tried..it is still failing

**Comment by cooktheryan** [comment]
Ami not found or ?

**Comment by kmurudi** [comment]
starts on workernode02 - 

The image id '[ami-1f8f8a09]' does not exist
--

**Comment by thoraxe** [comment]
Is this still a problem?

**Comment by kmurudi** [comment]
no
