### ISSUE TITLE
Experience with metrics is not that good since there are not that much of those.

### ISSUE THREAD

**Issue by tahonen** [openshift/openshift-cns-testdrive#274]
If you want to see interesting metrics, explore the Project for metrics itself, openshift-infra.

problem: one should say that we must wait for metrics to appear, when you open the "default project router Metrics" tab it's initially empty

**Comment by thoraxe** [comment]
metrics is going away in favor of prometheus and so we'll refocus on that, and I think Ed's PR will provide something cool.
