### ISSUE TITLE
Instructions about testing shared storage app are "misleading".

### ISSUE THREAD

**Issue by tahonen** [openshift/openshift-cns-testdrive#275]
workshop/ocp-admin-testdrive/module/cns-management

That’s it. You have successfully provided shared storage to pods throughout the entire system, therefore avoiding the need for data to be replicated at the application level to each pod.

problem: It looks like my uploaded file is not in the newly deployed pods.
Apparently we would have to upload another document for it to end up on persistent storage.
[cloud-user@master ~]$ oc login -u fancyuser1 -n my-shared-storage
[cloud-user@master ~]$ oc rsh file-uploader-2-ll91j ls -alh uploaded
total 8.0K
drwxrwsr-x. 4 root    2001 4.0K Mar  8 12:20 .
drwxrwxr-x. 7 default root  174 Mar  8 12:10 ..
drwxr-sr-x. 3 root    2001 4.0K Mar  8 12:19 .trashcan

**Comment by dmesser** [comment]
solved by update 3.9
