### ISSUE TITLE
Deleting a brick device in heketi sometimes hangs

### ISSUE THREAD

**Issue by dmesser** [openshift/openshift-cns-testdrive#285]
in CNS module, last step of "Replacing failed devices" chapter - preliminary investigation shows there is a vgremove command hanging somewhere.

**Comment by paddy667** [comment]
@dmesser Are you talking about the last command of the cns.adoc:
`heketi-cli device delete $FAILED_DEVICE_ID`
This command hanged for me and also lots of people who were apart of our lab yesterday.

**Comment by thoraxe** [comment]
this was an old CNS bug IIRC
