### ISSUE TITLE
default hosts template should have ldap for auth

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-cns-testdrive#29]
If we don't do the installation with LDAP for auth, it means the admin has to re-run the installer (albeit with -t master) later. This is a little bit... awkward.

I am thinking we may wish to install with LDAP auth out of the box.

* it won't affect the system:admin special user
* verification of installation can then include a simple "oc login" as a user
* module 2 can become LDAP setup and group manipulation
* module 3 can become CNS installation and configuration

Thoughts?

@cooktheryan 
@dmesser

**Comment by dmesser** [comment]
Ack. Let's go with IdM/LDAP integration out of the box.

**Comment by cooktheryan** [comment]
+1

**Comment by thoraxe** [comment]
Looks like this is in master:
https://github.com/openshift/openshift-cns-testdrive/blob/master/cloudformation/qwiklabs-cloudformation.yml#L581
