### ISSUE TITLE
Login as fancy-user1 for getting prometheus route

### ISSUE THREAD

**Issue by VeerMuchandi** [openshift/openshift-cns-testdrive#334]
In lab 5, the following section won’t work as the user logged in is `team-user1`. I think a login as `fancy-user1` is missing before this.

> Prometheus
> Now that you have a user with cluster-reader privileges (one that can see many administrative aspects of the cluster), we can revisit Prometheus and attempt to log-in to it.
> 
> Find the prometheus Route with the following command:
> 
> oc get route prometheus -n openshift-metrics

**Comment by thoraxe** [comment]
@VeerMuchandi would the PR referenced above fix it for you?

**Comment by VeerMuchandi** [comment]
yes it should
