### ISSUE TITLE
Environment specific tests - how to?

### ISSUE THREAD

**Issue by dmesser** [openshift/openshift-cns-testdrive#34]
When doing lab automation and verification we need to have access to the environment specific variables. E.g. the device name of the CNS bricks, the default routing suffix for OCP, the name of the project that we create for CNS? Some of this info could be just hard-coded in the lab guide and the automation but we may want to externalize that for easy updates later.

For the lab guide we are writing this info into /etc/sysconfig/workshopper on the guide node. But tests will likely need to be running from the master node, to get /etc/ansible/hosts as a second source for info.

What is the best way to get environment-specific information?

**Comment by thoraxe** [comment]
You could probably add another output file to one of the cloud-inits that "builds" a vars file for your playbook when the environment is provisioned.

Things like the devices for the CNS disks I do not think can easily be "detected".

**Comment by dmesser** [comment]
Now implemented using a generated file in /opt/lab/environment creating at CloudFormation runtime stage containing all information we can't easily deduce from the ansible inventory.
