### ISSUE TITLE
Scaling down machineset sometimes removes your terminal pod

### ISSUE THREAD

**Issue by christianh814** [openshift/openshift-cns-testdrive#436]
In [this section](https://github.com/openshift/openshift-cns-testdrive/blob/ocp4-dev/labguide/machinesets.adoc#cluster-scaling); the last thing  it has you do is scale the machine set down.

```
oc scale machineset cluster-5fa6-hx2ml-worker-us-east-2c -n openshift-machine-api --replicas=1
```
This has an interesting side effect on my install. So, sometimes, it chooses to delete the node/machine that the lab guide is running on (the terminal at least). When I come back up I have to follow the instructions on logging into the cluster and doing the git clone again.

Not sure how to mitigate this but here's a few ideas

1) Have the deployment run a [post deployment hook](https://docs.openshift.com/container-platform/4.1/applications/deployments/deployment-strategies.html#deployments-lifecycle-hooks_deployment-strategies) that does the git clone for you. That way when the pod "bounces" it has the content already
2) Build the terminal container with the lab manifests already built in (as a `COPY` or a `RUN` command (that git clones) inside the container on build)
3) Run the terminal with at least 2 pods using EFS for the content

Not sure what's best.

**Comment by christianh814** [comment]
cc: @kaovilai

**Comment by kaovilai** [comment]
@christianh814 couldn't repeat this one.

**Comment by christianh814** [comment]
I think this may have been a one off. I'll close this for now.
