### ISSUE TITLE
Moving the router to the infra node kills your session

### ISSUE THREAD

**Issue by christianh814** [openshift/openshift-cns-testdrive#437]
In [this section](https://github.com/openshift/openshift-cns-testdrive/blob/ocp4-dev/labguide/infra-nodes.adoc#router), when you move the router to the infra node; it will "kill" your session.

Nothing is "lost" so it's not as severe as #436 ; but you may want to call it out in the document

**Comment by christianh814** [comment]
CC: @kaovilai

**Comment by kaovilai** [comment]
Could you clarify this? Are you able to continue workshop or does it stop working?
For homeroom, when the terminal shows a closed connection, you can usually recover with a refresh. Everything in the terminal will be there if it is still running, but you may lose track on the content side and start from first page.

**Comment by christianh814** [comment]
You can "refresh" the page and still continue with the workshop. I guess the ask here is to call that out in the doc like 

```
NOTE: Your session may timeout during the router move. Please refresh the page to get your session back
```

Or something like that

**Comment by kaovilai** [comment]
I will test out if its the lab specifically. Terminal session will "close" whenever you have loss of internet connection at anypoint such as computer sleeping. It is possible that in a cat was walking by blocking Wi-Fi 🙀..
But a refresh would resolve this.

**Comment by christianh814** [comment]
Refresh is fine; but there should be a note to the user on the doc

**Comment by thoraxe** [comment]
@christianh814 that's weird. there should be at least 2 routers and they shouldn't get moved simultaneously. this might require an upstream bug on the router operator.
