### ISSUE TITLE
Cursor in integrated terminal does not work with line wrapped command

### ISSUE THREAD

**Issue by stencell** [openshift/openshift-cns-testdrive#447]
When using Chrome on MacOS, if you paste a command into the integrated terminal that wraps to multiple lines, you cannot use the cursor to move back and change part of the command when you need to adjust it for your environment. This makes it difficult when pasting longer commands from the lab guide, such as:
`oc scale machineset cluster-5fa6-hx2ml-worker-us-east-2c -n openshift-machine-api --replicas=2`.

**Comment by thoraxe** [comment]
This sounds like an upstream issue with homeroom

We'll see if Tiger can figure this out with Graham.

**Comment by stencell** [comment]
Sigh, of course it is working now. Same command, multiple different size windows, everything seems to be okay. I guess I'll chalk this up to environmental the other day.
