### ISSUE TITLE
Incorrect region and AZs for OCS MachineSets

### ISSUE THREAD

**Issue by stencell** [openshift/openshift-cns-testdrive#449]
When I create the `MachineSet` as instructed by the lab guide, it hard codes them to us-east-2. My cluster is deployed in `ap-southeast-1` region, so this will not work.

The `MachineSet` object definitions probably need to be more dynamically generated based on existing.

**Comment by thoraxe** [comment]
This is actually a bug. I think we only tested in us-east and the Summit experience was all deployed to us-east. Will raise this with GPTE.

**Comment by thoraxe** [comment]
Experience is now hard locked to east-2.
