### ISSUE TITLE
need to oc login as regular user to show project quota enforcement

### ISSUE THREAD

**Issue by jstakun** [openshift/openshift-cns-testdrive#453]
In LAB Project Template, Quota, and Limits
Create a New Project
before calling oc new-project template-test you need to oc login as regular user because kubeadmin will create project without quota

**Comment by kaovilai** [comment]
I think this would be a perfect place to add another component of guide to creating a test users and role bindings such that this test user can create projects with quota limits.
`oc create user test`
`oc create rolebinding`
and edit the rolebinding as necessary for what we need.

**Comment by thoraxe** [comment]
Why would we need to create a rolebinding for a user? The issue is more how to log in as a user that you create.

`oc new-project` should follow the project request template process regardless of whether or not a user is cluster-admin. If it doesn't that sounds like a bug in `oc`.

Are you sure that running `oc new-project` as a cluster admin (eg: kubeadmin) doesn't follow the process? Can you show us a reproducer @jstakun

**Comment by kaovilai** [comment]
Once you `oc create user test` you can run `oc create project --as-user=test` which without RoleBindings will fail as standard user lack permissions. 
Confirmed by `oc auth can-i create project --as-user=test`

**Comment by thoraxe** [comment]
why would a standard user lack permissions to create a project?

every user can create projects.

This sounds to me like `oc create user` does not involve the same process as what happens when a user logs in that doesn't already exist.

**Comment by kaovilai** [comment]
```
$ oc new-project hey --as=test
Error from server (Forbidden): To provision Projects you must request access in https://labs.opentlc.com or https://rhpds.redhat.com.
$ oc whoami --as=test
test
$ oc auth can-i create project --as=test
no
$ oc get user test -o yaml                       
apiVersion: user.openshift.io/v1
groups: null
identities: null
kind: User
metadata:
  creationTimestamp: "2019-08-01T17:54:27Z"
  name: test
  resourceVersion: "2579566"
  selfLink: /apis/user.openshift.io/v1/users/test
  uid: 67de21ae-b485-11e9-82d2-0a580a810025
```
Might be lack of identities when using `oc create user` as compared to opentlc-mgr
```
$ oc get user opentlc-mgr -o yaml    
apiVersion: user.openshift.io/v1
groups: null
identities:
- htpasswd_provider:opentlc-mgr
kind: User
metadata:
  creationTimestamp: "2019-07-29T15:22:44Z"
  name: opentlc-mgr
```

**Comment by thoraxe** [comment]
Would be good to ask the guys in #forum-master since they now own auth. It's too bad this didn't come up when @deads2k was still in the room!

**Comment by kaovilai** [comment]
It is possible that the RHPDS setup, based on the forbidden response that mentions to go to `labs.opentlc.com` that they customized the cluster so that only cluster-admin can create projects. asking in #forum-master

**Comment by thoraxe** [comment]
If you are talking about the shared RHPDS cluster then IIRC yes user project creation is disabled.

If you are talking about a workshop cluster that should not be the case.

**Comment by kaovilai** [comment]
The role that just allows creation of projects is the `self-provisioner` role and its subjects is the group `system:authenticated:oauth`.

Solution includes
- adding the new user we create during the lab to be an additional subject of this role
- them to create another cluster role from scratch and a rolebinding to bind the created user.

Here's the role's yaml
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: self-provisioner
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/self-provisioner
  uid: ca520e5c-b858-11e9-955b-062e5b45b858
  resourceVersion: '6199'
  creationTimestamp: '2019-08-06T14:45:10Z'
  annotations:
    openshift.io/description: A user that can request projects.
    rbac.authorization.kubernetes.io/autoupdate: 'true'
rules:
  - verbs:
      - create
    apiGroups:
      - ''
      - project.openshift.io
    resources:
      - projectrequests
```
