### ISSUE TITLE
Lab 7 chapter 1.1: how did you create VMs with more than one disk?

### ISSUE THREAD

**Issue by raffaelespazzoli** [openshift/openshift-cns-testdrive#460]
based on this: https://github.com/openshift/cluster-api-provider-aws/issues/231 the machine api operator for AWS does not support multiple disks.
I tried to follow the steps described in this module and the VMs are created with only one disks. the resulting ceph cluster has 0 byte capacity.
So this is more a question than an actual issue, but how were you able to create a ceph cluster with some capacity and actually create volumes out of it?

**Comment by raffaelespazzoli** [comment]
this is what I did to add a volume to the rook machines:
```
for machine in $(oc get machine -n openshift-machine-api | grep rook | awk '{print $1}'); do
  instance_id=$(oc get machine $machine -n openshift-machine-api -o jsonpath='{.status.providerStatus.instanceId}')
  echo working on machine $machine instance $instance_id
  availability_zone=$(oc get machine $machine -n openshift-machine-api -o jsonpath='{.spec.providerSpec.value.placement.availabilityZone}')
  region=$(oc get machine $machine -n openshift-machine-api -o jsonpath='{.spec.providerSpec.value.placement.region}')
  echo creating volume in availability zone $availability_zone and region $region
  volume_id=$(aws ec2 create-volume --region $region --availability-zone $availability_zone --volume-type=gp2 --size 200 --output json | jq -r .VolumeId)
  sleep 5
  echo attaching volume $volume_id to instance $instance_id 
  aws ec2 attach-volume --region $region --instance-id $instance_id --volume-id $volume_id --device /dev/sdr
done
```

**Comment by thoraxe** [comment]
my understanding of the lab was that @netzzer specifically chose an EC2 instance type that contains 2 disks OOTB, one of which was an SSD. The OCS lab was supposed to use that SSD for its storage for the very reason you stated (the cloud provider doesn't do multi-disk). we avoided using `aws` commands for some reason or another.

This was recently tested extensively and no one reported any failures. Despite seeing 0 bytes did all of the exercises work, or are you reporting a failure @raffaelespazzoli  ?

**Comment by raffaelespazzoli** [comment]
now I understand how you did it, thanks.
no failures.
