### ISSUE TITLE
[RFE] Infra operators should use taints/tolerations in order to ensure workload doesn't land on infra

### ISSUE THREAD

**Issue by raffaelespazzoli** [openshift/openshift-cns-testdrive#461]
the proposed approach is basically the same as described here: https://docs.openshift.com/container-platform/4.1/machine_management/creating-infrastructure-machinesets.html

this approach moves the infra workload to the infra machines but does not prevent the normal workload from landing on the infra machines as they still have the worker role.

I opened a doc issue about it: https://bugzilla.redhat.com/show_bug.cgi?id=1733230 but it was immediately closed.

Anyway for me this is still a gap.

**Comment by raffaelespazzoli** [comment]
I tried preventing normal workload from landing on infra nodes using taints and tolerations, but unfortunately our operators for deploying infra workloads do not support tolerations.
The only other strategy I could think of, is to change the node selector for normal workload projects to some new label what only normal workload nodes have.
this is painful and regardless should be explained by the article.

**Comment by thoraxe** [comment]
This is a known issue that requires taints/tolerations support within the cluster infra operators for their operands. when first written that support did not exist. it does now likely exist but we have not had time to update the labs for it.

**Comment by thoraxe** [comment]
additionally creating a default nodeselector and labeling existing machineset nodes as app would help.
