### ISSUE TITLE
Project missing LICENSE file.

### ISSUE THREAD

**Issue by kshithijiyer** [openshift/openshift-cns-testdrive#464]

**Comment by kaovilai** [comment]
Addressed in #434
The fixes will be merged eventually to ocp4-prod branch

@kshithijiyer do you need LICENSE in master branch?

**Comment by kshithijiyer** [comment]
> Addressed in #434
> The fixes will be merged eventually to ocp4-prod branch
> 
> @kshithijiyer do you need LICENSE in master branch?

Would be good to have.
