### ISSUE TITLE
On the Custom Resource Definition Overview page, select View Instances from the Actions menu. User may encounter 404 error and stuck there.

### ISSUE THREAD

**Issue by jumperwire** [openshift/openshift-cns-testdrive#478]
Exercise 8: On the Custom Resource Definition Overview page, select View Instances from the Actions menu. User may encounter 404 error and stuck there (the browser seems to cache the 404 error).

Workaround: In the 404 page, simply refresh the browser.

Consider adding additional instruction asking the user to refresh the browser.

**Comment by thoraxe** [comment]
Do you have a reproducer? Because I've never had this problem. And the instructions tell the user to refresh the page:

```
If you see a `404` error, don't panic. While the operator installation
succeeded, the operator itself has not finished installing and the
`CustomResourceDefinition` may not have been created yet. Wait a few moments
and then refresh the page.
```
