### ISSUE TITLE
MachineSets Lab command not showing INSTANCE in output

### ISSUE THREAD

**Issue by techjw** [openshift/openshift-cns-testdrive#480]
Branch: ocp4-dev
In the https://github.com/openshift/openshift-cns-testdrive/blob/ocp4-dev/workshop/content/machinesets.adoc the command `oc get machine -n openshift-machine-api` is shown producing output that includes the column `INSTANCE`. However, my current deployment of the workshop in OCP 4.2.7 (via RHPDS), that command is not showing the column.

**Comment by thoraxe** [comment]
Fixed by #499
