### ISSUE TITLE
Infra Nodes lab references sigs.k8s.io labels instead of machine.openshift.io

### ISSUE THREAD

**Issue by techjw** [openshift/openshift-cns-testdrive#481]
Branch: ocp4-dev
https://github.com/openshift/openshift-cns-testdrive/blob/ocp4-dev/workshop/content/infra-nodes.adoc has multiple references labels under sigs.k8s.io. However, under OCP 4.2.7, these values show up under machine.openshift.io

For example:
`2. Don’t change any instances of sigs.k8s.io/cluster-api-cluster: <clusterid>`
However the example YAML displays something like:
`machine.openshift.io/cluster-api-cluster: cluster-####`

**Comment by thoraxe** [comment]
Fixed by #498
