### ISSUE TITLE
LDAP lab attempts to login as incorrect admin user

### ISSUE THREAD

**Issue by techjw** [openshift/openshift-cns-testdrive#482]
Branch: ocp4-dev
https://github.com/openshift/openshift-cns-testdrive/blob/ocp4-dev/workshop/content/ldap-groupsync.adoc

Instructions in section `Create Projects for Collaboration` have the student switching back to the admin user after testing the LDAP users, but they are listing the incorrect user.

This service account does not exist:
`system:serviceaccount:labguide:admin-user`
Instead it should be:
`system:serviceaccount:lab-ocp-cns:dashboard-user`

**Comment by thoraxe** [comment]
Fixed by #498
