### ISSUE TITLE
Monitoring lab missing step to open Prometheus UI

### ISSUE THREAD

**Issue by techjw** [openshift/openshift-cns-testdrive#483]
Branch: ocp4-dev
https://github.com/openshift/openshift-cns-testdrive/blob/ocp4-dev/workshop/content/monitoring-basics.adoc

`Metrics UI (Prometheus Console)` section requires one more step to open the Prometheus UI console in OCP 4.2.7.
It should read something along these lines:
On the left hand side of the OpenShift Console, under the "Monitoring" section, click the link for "Metrics", then click the "Prometheus UI" link at the top of the Metrics page.

**Comment by thoraxe** [comment]
Fixed by #498
