### ISSUE TITLE
Mod3 Figure 1. OpenShift Pods does not show Image correctly

### ISSUE THREAD

**Issue by netzzer** [openshift/openshift-cns-testdrive#489]
The Image file is not rendering for Figure 1. OpenShift Pods,

**Comment by netzzer** [comment]
Mod3 Figure 2. OpenShift Service is also not rendering correctly.

**Comment by netzzer** [comment]
Mod3 Figure 3. OpenShift Route is also not rendering correctly.

**Comment by thoraxe** [comment]
Will be fixed when #499  merges
