### ISSUE TITLE
installation lab verification fails / checks for wrong node names

### ISSUE THREAD

**Issue by dmesser** [openshift/openshift-cns-testdrive#50]
`- name: Checking status of all the nodes to be 'Ready' 
      command: oc get -o jsonpath='{.status.conditions[?(@.reason=="KubeletReady")].type}' node {{ item }}
      with_items:
        - "{{ groups.nodes }}"
      register: status_of_node
      failed_when: "'Ready' not in status_of_node.stdout"  `

@kmurudi we cannot rely on the hostnames from the ansible inventory. They are different to the hostnames used by OpenShift. I suggest we use openshift_facts.yml supplied with openshift-ansible to determine the hostname.

**Comment by kmurudi** [comment]
after the PR #66 , the host names are not an issue currently for the checks.

**Comment by thoraxe** [comment]
So should we close this?

**Comment by kmurudi** [comment]
I think we can, but after someone else has tested it too

**Comment by dmesser** [comment]
fixed
