### ISSUE TITLE
Logging Module: Need to specify Elasticsearch version 4.2

### ISSUE THREAD

**Issue by techjw** [openshift/openshift-cns-testdrive#510]
There was a new version of the Elasticsearch operator pushed out, which failed to install during today's CCNRoadshow.  It may have been due to the operator not being fully available at registry.redhat.io, but we had to change from using the default install settings, to instead specifying version 4.2 (and obviously not 4.2-s390x)

**Comment by netzzer** [comment]
Issue is same for cluster-logging operator install. Need to specify version 4.2 or get failure for csv and ImageBackOff.

```
[~] $ oc get csv
NAME                                        DISPLAY                  VERSION              REPLACES
  PHASE
clusterlogging.4.3.0-202001211731           Cluster Logging          4.3.0-202001211731
  Installing
elasticsearch-operator.4.3.0-202001211731   Elasticsearch Operator   4.3.0-202001211731
  Installing
[~] $ oc get all
NAME                                            READY   STATUS             RESTARTS   AGE
pod/cluster-logging-operator-69585f6c7f-v2688   0/1     ImagePullBackOff   0          2m10s
```

**Comment by netzzer** [comment]
PR #513
