### ISSUE TITLE
OCS, Elasticsearch, Logging Operators fail to deploy using Console webUI in Homeroom

### ISSUE THREAD

**Issue by netzzer** [openshift/openshift-cns-testdrive#511]
If the lab user attempts to create the OCS, Elasticsearch, or Logging Operator using the Homeroom Console tab this will fail. User has to get to OCP console and login as Kubeadmin using provided password. 

From Homeroom Terminal window. This user does not have correct permissions.
```
[~] $ oc whoami
system:serviceaccount:lab-ocp-cns:dashboard-user
```

**Comment by thoraxe** [comment]
we are creating a user with `cluster-admin` privileges as part of deploying the lab guide:

https://github.com/redhat-cop/agnosticd/blob/development/ansible/roles/ocp4-workload-workshop-admin-storage/files/production-cluster-admin.json#L113-L133

`dashboard-user` has `cluster-admin` privileges. It would be interesting to know if the console is using the same user/service account, or if you somehow ended up in the web console as someone else. Can you validate?
