### ISSUE TITLE
ldap group sync validation failes

### ISSUE THREAD

**Issue by dmesser** [openshift/openshift-cns-testdrive#52]
@kmurudi 

`TASK [Checking if all the groups have been created by 'oc adm groups sync'] *********************************************
Tuesday 25 July 2017  11:13:28 -0400 (0:00:00.547)       0:00:00.637 **********
failed: [master.unset.ocp-admin.aws.openshifttestdrive.com] (item=ose-users) => {
    "changed": true,
    "cmd": [
        "oc",
        "get",
        "group",
        "ose-users"
    ],
    "delta": "0:00:00.201054",
    "end": "2017-07-25 11:13:29.162421",
    "failed": true,
    "item": "ose-users",
    "rc": 1,
    "start": "2017-07-25 11:13:28.961367"
}

STDERR:

Error from server (NotFound): groups "ose-users" not found`

Happens after successful execution of ldap_automation.yml

**Comment by kmurudi** [comment]
corrected typo and a task with - https://github.com/openshift/openshift-cns-testdrive/pull/53

**Comment by thoraxe** [comment]
Is this still an issue @kmurudi @dmesser ?

**Comment by dmesser** [comment]
Can't verify because I am running into #62

**Comment by kmurudi** [comment]
Worked for me in earlier deployment, but will have to check for #62 now first

**Comment by dmesser** [comment]
Fails for me with the following:

`TASK [Checking if all the groups have been created by 'oc adm groups sync'] *****************************************************************************************************************
Friday 04 August 2017  06:49:07 -0400 (0:00:00.565)       0:00:00.657 *********
failed: [master.internal.aws.testdrive.openshift.com] (item=ose-user) => {
    "changed": true,
    "cmd": [
        "oc",
        "get",
        "group",
        "ose-user"
    ],
    "delta": "0:00:00.216769",
    "end": "2017-08-04 06:49:08.254813",
    "failed": true,
    "item": "ose-user",
    "rc": 1,
    "start": "2017-08-04 06:49:08.038044"
}

STDERR:

Error from server (Forbidden): User "teamuser1" cannot get groups at the cluster scope

failed: [master.internal.aws.testdrive.openshift.com] (item=ose-normal-dev) => {
    "changed": true,
    "cmd": [
        "oc",
        "get",
        "group",
        "ose-normal-dev"
    ],
    "delta": "0:00:00.209247",
    "end": "2017-08-04 06:49:08.612416",
    "failed": true,
    "item": "ose-normal-dev",
    "rc": 1,
    "start": "2017-08-04 06:49:08.403169"
}

STDERR:

Error from server (Forbidden): User "teamuser1" cannot get groups at the cluster scope

failed: [master.internal.aws.testdrive.openshift.com] (item=ose-fancy-dev) => {
    "changed": true,
    "cmd": [
        "oc",
        "get",
        "group",
        "ose-fancy-dev"
    ],
    "delta": "0:00:00.206244",
    "end": "2017-08-04 06:49:08.971087",
    "failed": true,
    "item": "ose-fancy-dev",
    "rc": 1,
    "start": "2017-08-04 06:49:08.764843"
}

STDERR:

Error from server (Forbidden): User "teamuser1" cannot get groups at the cluster scope

failed: [master.internal.aws.testdrive.openshift.com] (item=ose-teamed-app) => {
    "changed": true,
    "cmd": [
        "oc",
        "get",
        "group",
        "ose-teamed-app"
    ],
    "delta": "0:00:00.206438",
    "end": "2017-08-04 06:49:09.326905",
    "failed": true,
    "item": "ose-teamed-app",
    "rc": 1,
    "start": "2017-08-04 06:49:09.120467"
}

STDERR:

Error from server (Forbidden): User "teamuser1" cannot get groups at the cluster scope`

**Comment by thoraxe** [comment]
This is a common problem when using Ansible to automate/test OpenShift. We forget to choose the right OpenShift user and assume we are running the right one! Looks like you were not a cluster admin. 

Kshitija should add a task at the beginning of the play that does a `oc login -u system:admin` to become the cluster administrator before performing these tests.

**Comment by thoraxe** [comment]
Temporary fix for you @dmesser is to perform that yourself before launching Ansible.

**Comment by kmurudi** [comment]
@thoraxe @dmesser  in the automation script - I have assigned role of 'cluster_admin' to group - ose-nromal-dev so, teamuser1.2 were able to access all the projects and do the verif tests

**Comment by thoraxe** [comment]
Dunno what fixed this but It's no longer a problem.
