### ISSUE TITLE
remove reference to glusterfs

### ISSUE THREAD

**Issue by ikke-t** [openshift/openshift-cns-testdrive#522]
Hi,

there is leftover text from older version which refers to GlusterFS.

In this doc: https://github.com/openshift/openshift-cns-testdrive/blob/ocp4-dev/workshop/content/template-quota-limits.adoc

it has the line:
> This setting limits the amount of storage that can be provisioned using the glusterfs-storage StorageClass.

I don't exactly know to which storage that should refer, block, object or nooba storage class, but likely not glusterfs-storage. Probably would need to be replaced with ```{{ CNS_STORAGECLASS }}```.

**Comment by netzzer** [comment]
This needs to be fixed:

This setting limits the amount of storage that can be provisioned using the glusterfs-storage StorageClass.

This setting limits the number of PersistentVolumeClaims for a StorageClass called {{ CNS_BLOCK_STORAGECLASS }}. A value of 0 means that creating PersistentVolumeClaims from this storage class is not allowed in this project.

**Comment by christianh814** [comment]
This is now fixed in the `ocp4-dev` branch.
