### ISSUE TITLE
cross-links to other Workshopper lab modules are not working

### ISSUE THREAD

**Issue by dmesser** [openshift/openshift-cns-testdrive#55]
Syntax taken from https://github.com/osevg/workshopper-content/blob/b1d50492022fd7071962507ac2a102a749dbc57c/configmap.adoc does not appear to work:

`In this lab, you will replace the environment variables provided in the
link:databases[previous labs] and use a `ConfigMap` instead to configure the
`nationalparks` application.`

**Comment by thoraxe** [comment]
@dmesser do you have an example code that you can demonstrate it's not working?

**Comment by dmesser** [comment]
@thoraxe 
.cns-management.adoc (line ~99)
```
This PVC has been automatically fulfilled by CNS because it's StorageClass was set up as the system-wide default in lab module link:cns-deploy["Deploying  Container-native Storage"]
```

The link get's translated to: http://labguide.<account-id>.aws.testdrive.openshift.com/cns-deploy which yields a 404 and should actually be: http://labguide.<account-id>.aws.testdrive.openshift.com/#/workshop/ocp-admin-testdrive/module/cns-deploy

In the workshopper repository an cross-reference link like this is included: 

.configmap.adoc (line 10)
```
In link:databases[previous labs] the `nationalparks` application was configured
with database credentials using environment variables
```

The link should get interpreted by using the string "link:" as the module name and construct the right path.

**Comment by thoraxe** [comment]
Referred upstream:
https://github.com/openshift-evangelists/workshopper/issues/41

I don't know that this was ever working, I guess...

**Comment by dmesser** [comment]
Will revert back to relative links. Done in #205

**Comment by thoraxe** [comment]
#205 was merged, so closing.
