### ISSUE TITLE
create separate Ansible inventories for different lab modules

### ISSUE THREAD

**Issue by dmesser** [openshift/openshift-cns-testdrive#58]
When adding nodes to the OpenShift cluster or nodes to the CNS topology it's best to use different Ansible inventory files to avoid side-effects of additional groups during OpenShift installation.

**Comment by thoraxe** [comment]
I'm not sure I follow. What do you mean "additional groups"? What would you want to have in a separate hosts file?

This kinda seems like an Ansible anti-pattern.
