### ISSUE TITLE
MachineSet name mismatch

### ISSUE THREAD

**Issue by blues-man** [openshift/openshift-cns-testdrive#600]
Hello,

just started the workshop from RHPDS and I saw from output the MachineSet name ends with `-1c` and not `-2c` as mentioned in the [guide](https://github.com/openshift/openshift-cns-testdrive/blob/ocp4-dev/workshop/content/machinesets.adoc):

```
oc get machines -n openshift-machine-api
NAME                                         PHASE     TYPE         REGION      ZONE         AGE
cluster-4bd2-flmk2-master-0                  Running   m5.xlarge    eu-west-1   eu-west-1a   140m
cluster-4bd2-flmk2-master-1                  Running   m5.xlarge    eu-west-1   eu-west-1b   140m
cluster-4bd2-flmk2-master-2                  Running   m5.xlarge    eu-west-1   eu-west-1c   140m
cluster-4bd2-flmk2-worker-eu-west-1a-f6pbd   Running   m5.2xlarge   eu-west-1   eu-west-1a   132m
cluster-4bd2-flmk2-worker-eu-west-1b-x6l5j   Running   m5.2xlarge   eu-west-1   eu-west-1b   132m
cluster-4bd2-flmk2-worker-eu-west-1c-5g9kx   Running   m5.2xlarge   eu-west-1   eu-west-1c   132m
```

**Comment by christianh814** [comment]
@blues-man The output will always been different. Is there something in the functionality that doesn't work because of the output?

**Comment by christianh814** [comment]
Ah I see this issue. This is because you ran the workshop in the EU region on AWS. Unfortunately we can't do anything about that :(
