### ISSUE TITLE
kibana index setup instructions are incorrect

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-cns-testdrive#604]
Steps listed are:

1. On the following screen, input `app*` as the index pattern, as shown below and hit Next Step.
2. On the following screen, input `infra*` as the index pattern, as shown below and hit Next Step.
3. On the next screen, select Timestamp in the drop-down box, as shown below:
4. Hit Create Index Pattern

When in fact, apparently, steps 3 and 4 should also be executed after step 1.

**Comment by christianh814** [comment]
@jchraibi PTAL
