### ISSUE TITLE
AMI id for "workerocs" MachineSet

### ISSUE THREAD

**Issue by bszeti** [openshift/openshift-cns-testdrive#607]
In the lab "OpenShift and Container Storage for Admins" the section "Deploying and Managing OpenShift Container Storage" creates a new MachineSet for OCS. The machine's AMI id in this file doesn't seem to work. https://github.com/openshift/openshift-cns-testdrive/blob/ocp4-dev/support/ocslab_cluster-workerocs.yaml#L34

Maybe there should be a step to update the id to the current cluster's worker node's AMI id.

**Comment by christianh814** [comment]
@bszeti Where are you using this YAML? This YAML isn't used in the workshop. Instead the AMI is gleaned from the following command

```bash
bash /opt/app-root/src/support/machineset-generator.sh 3 workerocs 0 | oc create -f -
oc get machineset -n openshift-machine-api -l machine.openshift.io/cluster-api-machine-role=workerocs -o name | xargs oc patch -n openshift-machine-api --type='json' -p '[{"op": "add", "path": "/spec/template/spec/metadata/labels", "value":{"node-role.kubernetes.io/worker":"", "role":"storage-node", "cluster.ocs.openshift.io/openshift-storage":""} }]'
oc get machineset -n openshift-machine-api -l machine.openshift.io/cluster-api-machine-role=workerocs -o name | xargs oc scale -n openshift-machine-api --replicas=1
```

Where are you seeing instructions to use this YAML?
