### ISSUE TITLE
Deployment not DepolymentConfig

### ISSUE THREAD

**Issue by akafoury1** [openshift/openshift-cns-testdrive#615]
Hello
the la guide is based on a deployment config within the image, but it seems that the image is updated and now using a deployment named mapit, so the application management basics section in the lad guide need to be updated accordingly

**Comment by christianh814** [comment]
@akafoury1 Where do you see that we're using deploymentconfig for mapit? It was changed in the doc, we only mention [`deploymentconfig`](https://github.com/openshift/openshift-cns-testdrive/blob/ocp4-dev/workshop/content/app-mgmt-basics.adoc#background-deployment-configurations-and-replica-sets) for historical reasons but there's nothing in the lab that manages it.

Can you point me to where you think there is an issue?

**Comment by christianh814** [comment]
Closed: Unable to reproduce
