### ISSUE TITLE
Update Elastic Operator description during install

### ISSUE THREAD

**Issue by renatoppuccini** [openshift/openshift-cns-testdrive#616]
As is:
Then follow the following steps:

Install the Elasticsearch Operator:

In the OpenShift console, click Operators → OperatorHub.

Choose Elasticsearch Operator from the list of available Operators, and click Install.

To be:
Then follow the following steps:

Install the OpenShift Elasticsearch Operator:

In the OpenShift console, click Operators → OperatorHub.

Choose OpenShift Elasticsearch Operator from the list of available Operators, and click Install.

**Comment by christianh814** [comment]
Fixed by https://github.com/openshift/openshift-cns-testdrive/pull/623
