### ISSUE TITLE
LDAP module doesn't work

### ISSUE THREAD

**Issue by blues-man** [openshift/openshift-cns-testdrive#662]
It looks like the user are not able to run through the *External (LDAP) Authentication Providers, Users, and Groups* module because the LDAP identity provider is not mapped properly:

```
[~] $ oc apply -f /opt/app-root/src/support/oauth-cluster.yaml
Warning: resource oauths/cluster is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by oc apply. oc apply should only be used on
resources created declaratively by either oc create --save-config or oc apply. The missing annotation will be patched automatically.
W0508 08:12:32.712194     758 warnings.go:70] unknown field "spec.identityProviders[0].challenge"
W0508 08:12:32.712314     758 warnings.go:70] unknown field "spec.identityProviders[0].login"
oauth.config.openshift.io/cluster configured
```
```
[~] $ oc login -u normaluser1 -p Op#nSh1ft
Login failed (401 Unauthorized)
```

Also after a long while it doesn't work. It doesn't show up also in the OpenShift Web Console as a list of identity provider configured

**Comment by jnewsome97** [comment]
Hi Natale,

Thanks for making us aware @blues-man. After working with the LDAP-team it wasn't an issue with the warnings it was an issue with godaddy's SSL. 

It was failing to connect so we separated out those commands today so it shouldn't be an issue in the future. Just requires clicking the wget command twice for whatever reason.

Thank you,
Josh
