### ISSUE TITLE
OpenShift client is outdated

### ISSUE THREAD

**Issue by dlbewley** [openshift/openshift-cns-testdrive#680]
The [Dockerfile](https://github.com/OpenShiftDemos/openshift-ops-workshops/blob/ocp4-dev/Dockerfile) pulls 4.9.18 version of the oc.

Other binaries are also stale.

**Comment by jnewsome97** [comment]
@dlbewley Thank you for bringing this to my attention. I'll take a look. 

Thanks @christianh814

**Comment by jnewsome97** [comment]
Updated/fixed. Thank you for adding this
